version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - mynet
  kafka:
    hostname: kafka
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - mynet
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - /var/lib/pgsql/data
      - C:/Users/zuzex/IdeaProjects/microservices-docker/docker/app/sql/create_dbs.sql:/docker-entrypoint-initdb.d/create_dbs.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - mynet
  citizens:
    image: docker.io/library/citizens:0.0.1-SNAPSHOT
    container_name: citizens
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/citizens
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
#      - 8081:8081
      - 8081
    restart: unless-stopped
    depends_on:
      - db
      - gateway
      - kafka
    networks:
      - mynet
  cars:
    image: docker.io/library/cars:0.0.1-SNAPSHOT
    container_name: cars
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cars
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
#      - 8082:8082
      - 8082
    restart: unless-stopped
    depends_on:
      - db
      - gateway
      - kafka
    networks:
      - mynet
  gateway:
    image: docker.io/library/gateway:0.0.1-SNAPSHOT
    container_name: gateway
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
