server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: citizens
          uri: http://citizens:8081
          predicates:
            - Path=/api/citizen/**
        - id: cars
          uri: http://cars:8082
          predicates:
            - Path=/api/car/**
