spring:
  application:
    name: cars
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cars
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
server:
  port: 8082
kafka-starter:
  port: localhost:29092
  group: city
  command: command
  result: result
  containerFactory: kafkaListenerContainerFactory
