##kafka.server.config=localhost:29092
##kafka.group.config=city
##kafka-starter:
##  port: localhost:29092
##  group: city
##  command: command
##  result: result
#spring:
#  kafka:
#    ## kafka consumer config ##
#    consumer:
#      bootstrap-servers: 'localhost:29092'
#      group-id: city
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
#      ## kafka producer config ##
#    producer:
#      bootstrap-servers: 'localhost:29092'
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    bootstrap-servers: 'localhost:29092'