spring:
  application:
    name: citizens
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/citizens
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
server:
  port: 8081
kafka-starter:
  port: kafka:9092
  group: city
  command: command
  result: result
  containerFactory: kafkaListenerContainerFactory

